### ISSUE TITLE
D-12 Setup passport.js and user schema for authentication

### ISSUE THREAD

**Issue by illonab** [TKPending/Doze#16]

**Comment by TKPending** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [D-12 Setup passport.js and user schema for authentication](https://trello.com/c/0WU096We/19-d-12-setup-passportjs-and-user-schema-for-authentication)

**Comment by TKPending** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [D-11 Create/Design Sign Up Page](https://trello.com/c/5AG4hupi/18-d-11-create-design-sign-up-page)
